"""add_cascade_delete_to_access_logs

Revision ID: 41de1f4adf09
Revises: 0f03176b1b4b
Create Date: 2026-07-16 10:58:08.756671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41de1f4adf09'
down_revision: Union[str, Sequence[str], None] = '0f03176b1b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('access_logs_vehicle_id_fkey'), 'access_logs', type_='foreignkey')
    op.create_foreign_key(None, 'access_logs', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_logs', type_='foreignkey')
    op.create_foreign_key(op.f('access_logs_vehicle_id_fkey'), 'access_logs', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
