"""add review_needed to access_logs

Revision ID: e329c4df53dd
Revises: 41de1f4adf09
Create Date: 2026-07-17 12:21:56.290130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e329c4df53dd'
down_revision: Union[str, Sequence[str], None] = '41de1f4adf09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('review_needed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'review_needed')
    # ### end Alembic commands ###
